# Generated by Django 4.0 on 2022-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100)),
                ('Roll', models.IntegerField()),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
    ]
